# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-30 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=15)),
                ('port', models.IntegerField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('connect_type', models.CharField(choices=[('HTTP', 'http'), ('HTTPS', 'https'), ('SOCKS4', 'socks4'), ('SOCKS5', 'socks5'), ('SSL', 'ssl')], default='HTTP', max_length=16)),
                ('status', models.CharField(choices=[('Available', 'available'), ('Unreachable', 'unreachable'), ('Unchecked', 'unchecked')], default='Unchecked', max_length=16)),
                ('anonymity', models.BooleanField(default=False)),
                ('ping', models.CharField(blank=True, max_length=64)),
                ('last_checked', models.DateTimeField(blank=True)),
            ],
        ),
    ]
